// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductionMeeting.Data;

#nullable disable

namespace ProductionMeeting.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260917135834_RemoveKpiSource")]
    partial class RemoveKpiSource
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ProductionMeeting.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Designation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("ProductionMeeting.Models.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentId"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DepartmentId");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            DepartmentId = 1,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Production"
                        },
                        new
                        {
                            DepartmentId = 2,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Quality"
                        },
                        new
                        {
                            DepartmentId = 3,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Maintenance"
                        });
                });

            modelBuilder.Entity("ProductionMeeting.Models.Indicator", b =>
                {
                    b.Property<int>("IndicatorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IndicatorId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IndicatorId");

                    b.ToTable("Indicators");

                    b.HasData(
                        new
                        {
                            IndicatorId = 1,
                            Code = "S",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Safety"
                        },
                        new
                        {
                            IndicatorId = 2,
                            Code = "Q",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Quality"
                        },
                        new
                        {
                            IndicatorId = 3,
                            Code = "C",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Cost"
                        },
                        new
                        {
                            IndicatorId = 4,
                            Code = "D",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Delivery"
                        },
                        new
                        {
                            IndicatorId = 5,
                            Code = "P",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Production"
                        },
                        new
                        {
                            IndicatorId = 6,
                            Code = "SUST",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Sustainability"
                        },
                        new
                        {
                            IndicatorId = 7,
                            Code = "M",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Morale"
                        },
                        new
                        {
                            IndicatorId = 8,
                            Code = "O",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Others"
                        });
                });

            modelBuilder.Entity("ProductionMeeting.Models.KpiMaster", b =>
                {
                    b.Property<int>("KpiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KpiId"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<int>("IndicatorId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("LineId")
                        .HasColumnType("int");

                    b.Property<bool>("LowerIsBetter")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PlantId")
                        .HasColumnType("int");

                    b.Property<int>("UnitId")
                        .HasColumnType("int");

                    b.HasKey("KpiId");

                    b.HasIndex("IndicatorId");

                    b.HasIndex("LineId");

                    b.HasIndex("UnitId");

                    b.HasIndex("PlantId", "LineId", "IndicatorId", "Description")
                        .IsUnique();

                    b.ToTable("KpiMasters");

                    b.HasData(
                        new
                        {
                            KpiId = 1,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "First Aid",
                            DisplayOrder = 1,
                            IndicatorId = 1,
                            IsActive = true,
                            LineId = 1,
                            LowerIsBetter = true,
                            PlantId = 1,
                            UnitId = 1
                        },
                        new
                        {
                            KpiId = 2,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Near Miss incidence",
                            DisplayOrder = 2,
                            IndicatorId = 1,
                            IsActive = true,
                            LineId = 1,
                            LowerIsBetter = true,
                            PlantId = 1,
                            UnitId = 1
                        },
                        new
                        {
                            KpiId = 3,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Fire Incidence",
                            DisplayOrder = 3,
                            IndicatorId = 1,
                            IsActive = true,
                            LineId = 1,
                            LowerIsBetter = true,
                            PlantId = 1,
                            UnitId = 1
                        },
                        new
                        {
                            KpiId = 4,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Offline Rework RPT XUV3XO",
                            DisplayOrder = 4,
                            IndicatorId = 2,
                            IsActive = true,
                            LineId = 1,
                            LowerIsBetter = true,
                            PlantId = 1,
                            UnitId = 1
                        },
                        new
                        {
                            KpiId = 5,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Offline Rework RPT XUV400",
                            DisplayOrder = 5,
                            IndicatorId = 2,
                            IsActive = true,
                            LineId = 1,
                            LowerIsBetter = true,
                            PlantId = 1,
                            UnitId = 1
                        },
                        new
                        {
                            KpiId = 6,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Buyoff Manpower Deployed",
                            DisplayOrder = 6,
                            IndicatorId = 2,
                            IsActive = true,
                            LineId = 1,
                            LowerIsBetter = true,
                            PlantId = 1,
                            UnitId = 6
                        },
                        new
                        {
                            KpiId = 7,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Rework Manpower Deployed",
                            DisplayOrder = 7,
                            IndicatorId = 2,
                            IsActive = true,
                            LineId = 1,
                            LowerIsBetter = true,
                            PlantId = 1,
                            UnitId = 6
                        },
                        new
                        {
                            KpiId = 8,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Process wise Zero Defect Stages *",
                            DisplayOrder = 8,
                            IndicatorId = 2,
                            IsActive = true,
                            LineId = 1,
                            LowerIsBetter = false,
                            PlantId = 1,
                            UnitId = 2
                        },
                        new
                        {
                            KpiId = 9,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Scrap Cost Process",
                            DisplayOrder = 9,
                            IndicatorId = 3,
                            IsActive = true,
                            LineId = 1,
                            LowerIsBetter = true,
                            PlantId = 1,
                            UnitId = 3
                        },
                        new
                        {
                            KpiId = 10,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Repairs & Maint. Cost Saving",
                            DisplayOrder = 10,
                            IndicatorId = 3,
                            IsActive = true,
                            LineId = 1,
                            LowerIsBetter = false,
                            PlantId = 1,
                            UnitId = 7
                        },
                        new
                        {
                            KpiId = 11,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Contract Labour",
                            DisplayOrder = 11,
                            IndicatorId = 3,
                            IsActive = true,
                            LineId = 1,
                            LowerIsBetter = true,
                            PlantId = 1,
                            UnitId = 6
                        },
                        new
                        {
                            KpiId = 12,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Traceability",
                            DisplayOrder = 12,
                            IndicatorId = 3,
                            IsActive = true,
                            LineId = 1,
                            LowerIsBetter = false,
                            PlantId = 1,
                            UnitId = 2
                        },
                        new
                        {
                            KpiId = 13,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Schedule Adh.",
                            DisplayOrder = 13,
                            IndicatorId = 4,
                            IsActive = true,
                            LineId = 1,
                            LowerIsBetter = false,
                            PlantId = 1,
                            UnitId = 2
                        },
                        new
                        {
                            KpiId = 14,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A Rank Breakdown",
                            DisplayOrder = 14,
                            IndicatorId = 4,
                            IsActive = true,
                            LineId = 1,
                            LowerIsBetter = true,
                            PlantId = 1,
                            UnitId = 1
                        },
                        new
                        {
                            KpiId = 15,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Minor Stoppages",
                            DisplayOrder = 15,
                            IndicatorId = 4,
                            IsActive = true,
                            LineId = 1,
                            LowerIsBetter = true,
                            PlantId = 1,
                            UnitId = 2
                        },
                        new
                        {
                            KpiId = 16,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Straight Pass Ratio",
                            DisplayOrder = 16,
                            IndicatorId = 4,
                            IsActive = true,
                            LineId = 1,
                            LowerIsBetter = false,
                            PlantId = 1,
                            UnitId = 2
                        },
                        new
                        {
                            KpiId = 17,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Non RFD Veh > 5 days",
                            DisplayOrder = 17,
                            IndicatorId = 4,
                            IsActive = true,
                            LineId = 1,
                            LowerIsBetter = true,
                            PlantId = 1,
                            UnitId = 1
                        },
                        new
                        {
                            KpiId = 18,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Eq.veh/man/year",
                            DisplayOrder = 18,
                            IndicatorId = 5,
                            IsActive = true,
                            LineId = 1,
                            LowerIsBetter = false,
                            PlantId = 1,
                            UnitId = 1
                        },
                        new
                        {
                            KpiId = 19,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Water",
                            DisplayOrder = 19,
                            IndicatorId = 6,
                            IsActive = true,
                            LineId = 1,
                            LowerIsBetter = true,
                            PlantId = 1,
                            UnitId = 4
                        },
                        new
                        {
                            KpiId = 20,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Power",
                            DisplayOrder = 20,
                            IndicatorId = 6,
                            IsActive = true,
                            LineId = 1,
                            LowerIsBetter = true,
                            PlantId = 1,
                            UnitId = 5
                        },
                        new
                        {
                            KpiId = 21,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Recognition of Associates through JIGYASA Portal",
                            DisplayOrder = 21,
                            IndicatorId = 7,
                            IsActive = true,
                            LineId = 1,
                            LowerIsBetter = false,
                            PlantId = 1,
                            UnitId = 1
                        },
                        new
                        {
                            KpiId = 22,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Ergonomy Status",
                            DisplayOrder = 22,
                            IndicatorId = 7,
                            IsActive = true,
                            LineId = 1,
                            LowerIsBetter = false,
                            PlantId = 1,
                            UnitId = 9
                        },
                        new
                        {
                            KpiId = 23,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Highlights/Lowlights/Others",
                            DisplayOrder = 23,
                            IndicatorId = 8,
                            IsActive = true,
                            LineId = 1,
                            LowerIsBetter = false,
                            PlantId = 1,
                            UnitId = 1
                        },
                        new
                        {
                            KpiId = 24,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "CCTV Camera Working Status",
                            DisplayOrder = 24,
                            IndicatorId = 8,
                            IsActive = true,
                            LineId = 1,
                            LowerIsBetter = false,
                            PlantId = 1,
                            UnitId = 1
                        });
                });

            modelBuilder.Entity("ProductionMeeting.Models.KpiTransaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionId"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("F26Value")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("F27Value")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("KpiId")
                        .HasColumnType("int");

                    b.Property<int?>("ModelId")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("MonthCumValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SessionId")
                        .HasColumnType("int");

                    b.Property<decimal?>("WeekValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("YtdValue")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("TransactionId");

                    b.HasIndex("KpiId");

                    b.HasIndex("ModelId");

                    b.HasIndex("SessionId", "KpiId", "ModelId")
                        .IsUnique()
                        .HasFilter("[ModelId] IS NOT NULL");

                    b.ToTable("KpiTransactions");
                });

            modelBuilder.Entity("ProductionMeeting.Models.KpiTransactionAudit", b =>
                {
                    b.Property<int>("AuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuditId"));

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChangedByUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("ChangedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KpiId")
                        .HasColumnType("int");

                    b.Property<string>("NewValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TransactionId")
                        .HasColumnType("int");

                    b.HasKey("AuditId");

                    b.HasIndex("ChangedByUserId");

                    b.HasIndex("TransactionId");

                    b.ToTable("KpiTransactionAudits");
                });

            modelBuilder.Entity("ProductionMeeting.Models.MeetingSession", b =>
                {
                    b.Property<int>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SessionId"));

                    b.Property<string>("ConductedByUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("LineId")
                        .HasColumnType("int");

                    b.Property<DateTime>("MeetingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PlantId")
                        .HasColumnType("int");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ShiftId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("SessionId");

                    b.HasIndex("ConductedByUserId");

                    b.HasIndex("LineId");

                    b.HasIndex("ShiftId");

                    b.HasIndex("PlantId", "LineId", "MeetingDate")
                        .IsUnique();

                    b.ToTable("MeetingSessions");
                });

            modelBuilder.Entity("ProductionMeeting.Models.Plant", b =>
                {
                    b.Property<int>("PlantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlantId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PlantId");

                    b.ToTable("Plants");

                    b.HasData(
                        new
                        {
                            PlantId = 1,
                            Code = "MAH-XUV",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Mahindra - XUV Plant"
                        });
                });

            modelBuilder.Entity("ProductionMeeting.Models.ProductModel", b =>
                {
                    b.Property<int>("ModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ModelId"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ModelId");

                    b.ToTable("ProductModels");

                    b.HasData(
                        new
                        {
                            ModelId = 1,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "XUV300"
                        },
                        new
                        {
                            ModelId = 2,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "XUV3XO"
                        },
                        new
                        {
                            ModelId = 3,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "XUV400"
                        });
                });

            modelBuilder.Entity("ProductionMeeting.Models.ProductionLine", b =>
                {
                    b.Property<int>("LineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LineId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PlantId")
                        .HasColumnType("int");

                    b.HasKey("LineId");

                    b.HasIndex("PlantId", "Code")
                        .IsUnique();

                    b.ToTable("ProductionLines");

                    b.HasData(
                        new
                        {
                            LineId = 1,
                            Code = "TCF",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "XUV TCF Line",
                            PlantId = 1
                        });
                });

            modelBuilder.Entity("ProductionMeeting.Models.Shift", b =>
                {
                    b.Property<int>("ShiftId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShiftId"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan?>("EndTime")
                        .HasColumnType("time");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan?>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("ShiftId");

                    b.ToTable("Shifts");

                    b.HasData(
                        new
                        {
                            ShiftId = 1,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "General"
                        },
                        new
                        {
                            ShiftId = 2,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Shift A"
                        },
                        new
                        {
                            ShiftId = 3,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Shift B"
                        },
                        new
                        {
                            ShiftId = 4,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Shift C"
                        });
                });

            modelBuilder.Entity("ProductionMeeting.Models.Unit", b =>
                {
                    b.Property<int>("UnitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UnitId"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UnitId");

                    b.ToTable("Units");

                    b.HasData(
                        new
                        {
                            UnitId = 1,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Nos"
                        },
                        new
                        {
                            UnitId = 2,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "%"
                        },
                        new
                        {
                            UnitId = 3,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Rs./Veh"
                        },
                        new
                        {
                            UnitId = 4,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Ltrs/Veh"
                        },
                        new
                        {
                            UnitId = 5,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Units/Veh"
                        },
                        new
                        {
                            UnitId = 6,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Nos/Shift"
                        },
                        new
                        {
                            UnitId = 7,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Rs. Lacs"
                        },
                        new
                        {
                            UnitId = 8,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Nos/Month"
                        },
                        new
                        {
                            UnitId = 9,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "No. of Stages"
                        });
                });

            modelBuilder.Entity("ProductionMeeting.Models.UserPlantLineAccess", b =>
                {
                    b.Property<int>("AccessId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccessId"));

                    b.Property<int?>("LineId")
                        .HasColumnType("int");

                    b.Property<int>("PlantId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("AccessId");

                    b.HasIndex("LineId");

                    b.HasIndex("PlantId");

                    b.HasIndex("UserId", "PlantId", "LineId")
                        .IsUnique()
                        .HasFilter("[LineId] IS NOT NULL");

                    b.ToTable("UserPlantLineAccesses");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ProductionMeeting.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ProductionMeeting.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProductionMeeting.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ProductionMeeting.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProductionMeeting.Models.KpiMaster", b =>
                {
                    b.HasOne("ProductionMeeting.Models.Indicator", "Indicator")
                        .WithMany()
                        .HasForeignKey("IndicatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProductionMeeting.Models.ProductionLine", "Line")
                        .WithMany()
                        .HasForeignKey("LineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProductionMeeting.Models.Plant", "Plant")
                        .WithMany()
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProductionMeeting.Models.Unit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Indicator");

                    b.Navigation("Line");

                    b.Navigation("Plant");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("ProductionMeeting.Models.KpiTransaction", b =>
                {
                    b.HasOne("ProductionMeeting.Models.KpiMaster", "Kpi")
                        .WithMany()
                        .HasForeignKey("KpiId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProductionMeeting.Models.ProductModel", "Model")
                        .WithMany()
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ProductionMeeting.Models.MeetingSession", "Session")
                        .WithMany("Transactions")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kpi");

                    b.Navigation("Model");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("ProductionMeeting.Models.KpiTransactionAudit", b =>
                {
                    b.HasOne("ProductionMeeting.Models.ApplicationUser", "ChangedBy")
                        .WithMany()
                        .HasForeignKey("ChangedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProductionMeeting.Models.KpiTransaction", "Transaction")
                        .WithMany()
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChangedBy");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("ProductionMeeting.Models.MeetingSession", b =>
                {
                    b.HasOne("ProductionMeeting.Models.ApplicationUser", "ConductedBy")
                        .WithMany()
                        .HasForeignKey("ConductedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProductionMeeting.Models.ProductionLine", "Line")
                        .WithMany()
                        .HasForeignKey("LineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProductionMeeting.Models.Plant", "Plant")
                        .WithMany()
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProductionMeeting.Models.Shift", "Shift")
                        .WithMany()
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ConductedBy");

                    b.Navigation("Line");

                    b.Navigation("Plant");

                    b.Navigation("Shift");
                });

            modelBuilder.Entity("ProductionMeeting.Models.ProductionLine", b =>
                {
                    b.HasOne("ProductionMeeting.Models.Plant", "Plant")
                        .WithMany("ProductionLines")
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("ProductionMeeting.Models.UserPlantLineAccess", b =>
                {
                    b.HasOne("ProductionMeeting.Models.ProductionLine", "Line")
                        .WithMany()
                        .HasForeignKey("LineId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ProductionMeeting.Models.Plant", "Plant")
                        .WithMany()
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProductionMeeting.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Line");

                    b.Navigation("Plant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProductionMeeting.Models.MeetingSession", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("ProductionMeeting.Models.Plant", b =>
                {
                    b.Navigation("ProductionLines");
                });
#pragma warning restore 612, 618
        }
    }
}
